/* AUTHENTICATION */
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

/* REGISTRATION */
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';

export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

/* ITEMS */
export const ITEMS_REQUEST = 'ITEMS_REQUEST';

export const ITEMS_FAILURE = 'ITEMS_FAILURE';

export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';

/* ITEM */
export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST';

export const ITEM_CREATE_FAILURE = 'ITEM_CREATE_FAILURE';

export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';

/* EDIT */
export const ITEM_EDIT_REQUEST = 'ITEM_EDIT_REQUEST';

export const ITEM_EDIT_FAILURE = 'ITEM_EDIT_FAILURE';

export const ITEM_EDIT_SUCCESS = 'ITEM_EDIT_SUCCESS';

/* Mark Complete */
export const ITEM_MARK_COMPLETE_REQUEST = 'ITEM_MARK_COMPLETE_REQUEST';

export const ITEM_MARK_COMPLETE_FAILURE = 'ITEM_MARK_COMPLETE_FAILURE';

export const ITEM_MARK_COMPLETE_SUCCESS = 'ITEM_MARK_COMPLETE_SUCCESS';
