/* ITEM */
export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST';

export const ITEM_CREATE_FAILURE = 'ITEM_CREATE_FAILURE';

export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';

/* EDIT */
export const ITEM_EDIT = 'ITEM_EDIT';

export const ITEM_EDIT_CLOSE = 'ITEM_EDIT_CLOSE';

export const ITEM_EDIT_REQUEST = 'ITEM_EDIT_REQUEST';

export const ITEM_EDIT_FAILURE = 'ITEM_EDIT_FAILURE';

export const ITEM_EDIT_SUCCESS = 'ITEM_EDIT_SUCCESS';

/* Mark Complete */
export const ITEM_MARK_COMPLETE_REQUEST = 'ITEM_MARK_COMPLETE_REQUEST';

export const ITEM_MARK_COMPLETE_FAILURE = 'ITEM_MARK_COMPLETE_FAILURE';

export const ITEM_MARK_COMPLETE_SUCCESS = 'ITEM_MARK_COMPLETE_SUCCESS';