# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=240, null=True),
        ),
    ]
